# Competition configuration options

drops:
  drop_region:
    min:
      xyz: [0.0, 2.7, 0.6]
    max:
      xyz: [0.6, 3.5, 2.0]
  dropped_parts:
    unreachable:
      part_type_to_drop: order_part1
      destination:
        xyz: [0.6, 3.1, 1.0]
    reachable:
      part_type_to_drop: order_part2
      destination:
        xyz: [0.9, 2.8, 0.9]
        rpy: [0, 0, 0.5]
    impeding:
      part_type_to_drop: order_part3
      destination:
        xyz: [0.2, 3.0, 0.9]
        rpy: [0, 0, 0.5]

options:
  spawn_extra_models: true # start with part in gripper
  model_type_aliases:
    order_part1: part4
    order_part2: part3
    order_part3: part4

models_to_spawn:
  world:
    models:
      part_to_drop:
        type: order_part1
        pose:
          xyz: [0.1, 2.5, 1.6]
          rpy: [0, 0, 0]
